version: '3'

networks:
  parvum:
    name: ${PARVUM_NETWORK}
    external: true
  sail:
    driver: bridge

services:
  laravel:
    image: '${PARVUM_IMAGE}'
    container_name: parvum.users-${PARVUM_VERSION}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'parvum.events:${PARVUM_SERVICE_EVENTS_IP}'
    networks:
      sail:
      parvum:
        ipv4_address: ${PARVUM_IPV4_ADDRESS}
    depends_on:
      - pgsql
  pgsql:
    image: 'postgres:15'
    environment:
        PGPASSWORD: 'password'
        POSTGRES_DB: 'parvum_users'
        POSTGRES_USER: 'users'
        POSTGRES_PASSWORD: 'password'
    volumes:
      - 'sail-pgsql:/var/lib/postgresql/data'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "parvum_users", "-U", "users" ]
      retries: 3
      timeout: 5s
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    restart: always
    volumes:
      - ./dynamodblocal-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    networks:
      - sail
volumes:
  sail-pgsql:
    driver: local
