version: 2.1

jobs:
  release-version:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f5:41:b7:cf:99:0e:1e:39:d7:de:dd:2a:1a:76:7d:74"
      - run:
          shell: "/bin/bash"
          name: "Install dependencies"
          command: "yarn --frozen-lockfile"
      - run:
          shell: "/bin/bash"
          name: "Launch version"
          command: |
            export GITHUB_TOKEN="$GITHUB_TOKEN"
            npx semantic-release
      - run: mkdir -p semantic-release-workspace
      - run: echo $(node -e "console.log(require('./package.json').version)") > semantic-release-workspace/released-version
      - persist_to_workspace:
          root: semantic-release-workspace
          paths:
            - released-version

  dockerhub-publish:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/semantic-release-workspace
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          shell: "/bin/bash"
          name: "Build image"
          command: docker build -t=parvum-release -f parvum.Dockerfile .
      - run:
          shell: "/bin/bash"
          name: "Push to DockerHub"
          command: |
            export RELEASED_VERSION=$(cat /tmp/semantic-release-workspace/released-version)
            docker tag parvum-release:latest kiske/users:$RELEASED_VERSION
            docker push kiske/users:$RELEASED_VERSION
            

workflows:
  release-version-workflow:
    jobs:
      - release-version:
          context:
            - gh-parvum
          filters:
            branches:
              only: /main|beta|alpha/
      - dockerhub-publish:
          context:
            - gh-parvum
          filters:
            branches:
              only: /main|beta|alpha/
          requires:
            - release-version

